services:
  mysql:
    image: 'mysql:8.3.0'
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USER}
    ports:
      - '3306:3306'
    command:
      --default-authentication-plugin=mysql_native_password