name: FreezeAlarm Spring Boot CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
      - name: Start Docker Compose
        run: docker-compose -f backend/compose.yaml up -d
      - name: Wait for MySQL to be ready
        run: |
          for i in {1..10}; do
            docker exec mysql_db mysqladmin ping -h localhost --silent && break
            echo "Waiting for MySQL..."
            sleep 10
          done
      - name: Test
        run: mvn -B package -f backend/pom.xml