name: FreezeAlarm Spring Boot CI pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21  # Use JDK 21 (or JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven


      - name: Build without tests
        run: mvn -B clean package -DskipTests -f backend/pom.xml

