name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker Compose
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Start MySQL
        run: docker-compose up -d
        working-directory: backend

      - name: Wait for MySQL to be ready
        run: npx wait-on tcp:3306

      - name: Start Backend Server
        run: mvn spring-boot:run -f pom.xml &
        working-directory: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Build Vite Project
        run: npm run build
        working-directory: frontend

      - name: Start Vite Preview Server
        run: npm run preview &
        working-directory: frontend

      - name: Wait for services to be ready
        run: npx wait-on http-get://localhost:5173 http-get://localhost:8080

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: frontend

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
