name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Docker & Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose-plugin

      - name: Start MySQL
        run: docker compose up -d
        working-directory: backend

      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do
            if docker exec mysql_db mysqladmin ping -h localhost --silent; then
              echo "MySQL is up!"
              exit 0
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done
          echo "MySQL did not start in time!" && exit 1

      - name: Start Backend Server
        run: mvn spring-boot:run -f pom.xml &
        working-directory: backend

      - name: Wait for Backend to be ready
        run: npx wait-on tcp:localhost:8080

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend

      - name: Build Vite Project
        run: npm run build
        working-directory: frontend

      - name: Start Vite Preview Server
        run: npm run preview &
        working-directory: frontend

      - name: Wait for Frontend to be ready
        run: npx wait-on tcp:localhost:5173

      - name: Run Playwright tests
        run: npx playwright test
        working-directory: frontend

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30
